#!/bin/bash

#SSH to EC2 Machine created above
sudo apt update -y

#Install Openjdk Java 17
sudo apt install -y openjdk-21-jdk

#Install Jenkins with bellow commands 

sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install -y jenkins

#Start Jenkins application suing systemctl

#sudo systemctl start jenkins 

#sudo systemctl stop jenkins 

#sudo systemctl status jenkins 
